using FastColoredTextBoxNS;
using RegexerV2;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Windows.Forms;
using Range = FastColoredTextBoxNS.Range;

namespace RegexerUIV2
{
    public class FctbManager
    {
        public static readonly Brush BaseBrush = Brushes.Gainsboro;
        public static readonly Brush BaseBrushLight = new SolidBrush(Color.FromArgb(235, 235, 235));
        public static readonly Brush TransparentBrush = new SolidBrush(Color.Transparent);
        public static readonly SolidBrush MatchPositionBrush = new SolidBrush(Color.DarkGray);
        public const StyleIndex BaseStyleIndex = StyleIndex.Style0;
        public const StyleIndex ErrorStyleIndex = StyleIndex.Style3;
        private readonly TextStyle BaseStyle = new(null, BaseBrush, FontStyle.Bold);
        private static readonly TextStyle[] IndividualMatchStyles =
        [
            //Generated by Claude Haiku 4.5
            new (new SolidBrush(Color.FromArgb(0, 0, 139)), BaseBrush, FontStyle.Bold),        // Dark Blue
            new (new SolidBrush(Color.FromArgb(0, 100, 0)), BaseBrush, FontStyle.Bold),        // Dark Green
            new (new SolidBrush(Color.FromArgb(192, 0, 0)), BaseBrush, FontStyle.Bold),        // Dark Red
            new (new SolidBrush(Color.FromArgb(184, 134, 11)), BaseBrush, FontStyle.Bold),     // Dark Goldenrod
            new (new SolidBrush(Color.FromArgb(128, 0, 128)), BaseBrush, FontStyle.Bold),      // Purple
            new (new SolidBrush(Color.FromArgb(139, 69, 19)), BaseBrush, FontStyle.Bold),      // Saddle Brown
            new (new SolidBrush(Color.FromArgb(0, 128, 128)), BaseBrush, FontStyle.Bold),      // Teal
            new (new SolidBrush(Color.FromArgb(105, 105, 105)), BaseBrush, FontStyle.Bold),    // Dim Gray
            new (new SolidBrush(Color.FromArgb(139, 0, 139)), BaseBrush, FontStyle.Bold),      // Dark Magenta
            new (new SolidBrush(Color.FromArgb(85, 107, 47)), BaseBrush, FontStyle.Bold),      // Dark Olive Green
            new (new SolidBrush(Color.FromArgb(47, 79, 79)), BaseBrush, FontStyle.Bold),       // Dark Slate Gray
            new (new SolidBrush(Color.FromArgb(25, 25, 112)), BaseBrush, FontStyle.Bold),      // Midnight Blue
            new (new SolidBrush(Color.FromArgb(178, 34, 34)), BaseBrush, FontStyle.Bold),      // Firebrick
            new (new SolidBrush(Color.FromArgb(75, 0, 130)), BaseBrush, FontStyle.Bold),       // Indigo
            new (new SolidBrush(Color.FromArgb(128, 0, 0)), BaseBrush, FontStyle.Bold),        // Maroon

            //The below have been excluded because FastColoredTextBox only supports 16 styles for each textbox

            //new (new SolidBrush(Color.FromArgb(0, 128, 64)), BaseBrush, FontStyle.Bold),       // Dark Cyan-Green
            //new (new SolidBrush(Color.FromArgb(220, 20, 60)), BaseBrush, FontStyle.Bold),      // Crimson
            //new (new SolidBrush(Color.FromArgb(102, 51, 153)), BaseBrush, FontStyle.Bold),     // Dark Purple
            //new (new SolidBrush(Color.FromArgb(102, 102, 0)), BaseBrush, FontStyle.Bold),      // Dark Olive
            //new (new SolidBrush(Color.FromArgb(34, 139, 34)), BaseBrush, FontStyle.Bold),      // Forest Green
        ];

        private readonly Regexer _regexer = new (TimeSpan.Zero); //Regex actually never gets used, so these constructor arguments don't matter.
        private readonly Dictionary<Style, StyleIndex> _allStyles = new();
        private readonly HashSet<string> _patternLabels = new();
        private readonly HashSet<string> _patternUmLabels = new();
        private readonly Dictionary<string, StyleIndex> _labelStyleIndices = new();
        private readonly Dictionary<string, SolidBrush> _labelStyleBrushes = new();
        private readonly List<int> _findStylingOrder = new();
        private readonly List<int> _replaceStylingOrder = new();
        private List<SyntaxStructure.SuggestionToken> _suggestionTokens = [];
        private bool _showSuggestionsOnCommand;
        private bool _monoColouredHighlight;

        public void SetupTextBoxStyles(FastColoredTextBox inputTextBox, FastColoredTextBox outputTextBox)
        {
            inputTextBox.AddStyle(BaseStyle);
            outputTextBox.AddStyle(BaseStyle);
            foreach (var individualMatchStyle in IndividualMatchStyles)
            {
                inputTextBox.AddStyle(individualMatchStyle);
                outputTextBox.AddStyle(individualMatchStyle);
            }
        }

        public void SetupPatternTextBoxes(FastColoredTextBox findTextBox, FastColoredTextBox replaceTextBox)
        {
            InitializeStyles(findTextBox, true);
            InitializeStyles(replaceTextBox, false);
            InitializePopup(findTextBox, false);
            InitializePopup(replaceTextBox, true);
            return;

            void InitializeStyles(FastColoredTextBox textBox, bool first)
            {
                textBox.AddStyle(BaseStyle);
                foreach (Style style in Enum.GetValues(typeof(Style)))
                {
                    var textStyle = style switch
                    {
                        Style.Escape => new TextStyle(Brushes.DarkGray, null, FontStyle.Regular),
                        Style.Label => BaseStyle,
                        Style.Separator => new TextStyle(Brushes.BlueViolet, BaseBrush, FontStyle.Bold),
                        Style.KeyLetter => new TextStyle(Brushes.CornflowerBlue, BaseBrush, FontStyle.Bold),
                        Style.Regex => new TextStyle(Brushes.Brown, BaseBrush, FontStyle.Bold),
                        Style.BaseLight => new TextStyle(null, BaseBrushLight, FontStyle.Regular),
                        _ => throw new ArgumentOutOfRangeException()
                    };
                    var styleIndex = Range.ToStyleIndex(textBox.AddStyle(textStyle));
                    if(first) _allStyles.Add(style, styleIndex);
                }
            }

            void InitializePopup(FastColoredTextBox textBox, bool isReplacePattern)
            {
                var autocomplete = new AutocompleteMenu(textBox);
                autocomplete.SearchPattern = @"[^\r\n]";
                autocomplete.AlwaysShowTooltip = true;
                autocomplete.SelectedColor = Color.LightBlue;
                //const int autoCompleteWidth = 250;
                //autocomplete.Items.MaximumSize = autocomplete.Items.MaximumSize with { Width = autoCompleteWidth };
                //autocomplete.Items.Width = autoCompleteWidth;
                //autocomplete.MinFragmentLength = 0;
                autocomplete.ToolTipDuration = 0;
                autocomplete.Items.NoSpacingForIcons = true;
                autocomplete.Items.AutoWidth = true;
                autocomplete.Items.UseSolidBrushForSelected = true;
                autocomplete.Items.ReShowMenuAfterSelected = true;
                autocomplete.MaxTooltipSize = new Size(300, 0);
                autocomplete.Items.SetAutocompleteItems(new Intellisense(textBox, autocomplete, isReplacePattern, 
                    () => _patternLabels.OrderBy(l => l),
                    () => _suggestionTokens,
                    () => _showSuggestionsOnCommand));
            }
        }

        public void HighlightAndSuggest(FastColoredTextBox textBox, bool isReplacePattern)
        {
            IEnumerable<SyntaxStructure.Token>? tokens;
            if (textBox.Range.End == textBox.Selection.End)
            {
                (tokens, _suggestionTokens) = _regexer.ParsePatternWithSuggestions(textBox.Text, isReplacePattern);
            }
            else
            {
                tokens = _regexer.ParsePattern(textBox.Text, isReplacePattern);
                var fragmentBeforeCursor = textBox.Range.GetIntersectionWith(new Range(textBox, textBox.Range.Start, textBox.Selection.End));
                _suggestionTokens = fragmentBeforeCursor.Length == 0 ? []
                    : _regexer.ParsePatternWithSuggestions(textBox.Text, 0, fragmentBeforeCursor.Length, isReplacePattern).Suggestions;
            }
            HighlightPatternSyntax(textBox, tokens!, isReplacePattern);
        }

        public void HighlightPatternSyntax(FastColoredTextBox textBox, IEnumerable<SyntaxStructure.Token> tokens, bool isReplacePattern)
        {
            foreach (var styleIndex in _allStyles.Values)
            {
                textBox.Range.ClearStyle(styleIndex);
            }
            if (!isReplacePattern)
            {
                _patternLabels.Clear();
                _patternUmLabels.Clear();
            }
            Highlight(tokens);
            void Highlight(IEnumerable<SyntaxStructure.Token> tokens)
            {
                var tokensArray = tokens.ToArray();
                foreach (var token in tokensArray)
                {
                    switch (token)
                    {
                        case SyntaxStructure.FreeTextToken freeTextToken:
                            if(freeTextToken.Name == SyntaxStructure.TokenName.PlainText)
                                textBox.GetRange(freeTextToken.Index, freeTextToken.Index + freeTextToken.Length).SetStyle(_allStyles[Style.Regex]);
                            else if (freeTextToken.Name == SyntaxStructure.TokenName.Label && !isReplacePattern)
                            {
                                var label = textBox.Text.Substring(freeTextToken.Index, freeTextToken.Length);
                                _patternLabels.Add(label);
                                if (tokensArray.Length > 3 && textBox.Text.AsSpan(tokensArray[3].Index, tokensArray[3].Length) is "u" or "m")
                                    _patternUmLabels.Add(label);
                            }
                            foreach (var escapeIndex in freeTextToken.EscapeIndices)
                                textBox.GetRange(escapeIndex, escapeIndex + 1).SetStyle(_allStyles[Style.Escape]);
                            break;
                        case SyntaxStructure.ComplexToken complexToken:
                            switch (complexToken.Name)
                            {
                                case SyntaxStructure.TokenName.SingleLineStructure:
                                    textBox.GetRange(complexToken.Index, complexToken.Index + complexToken.Length).SetStyle(_allStyles[Style.BaseLight]);
                                    break;
                                case SyntaxStructure.TokenName.Pattern:
                                case SyntaxStructure.TokenName.MatchMultipleSpread:
                                    textBox.GetRange(complexToken.Index, complexToken.Index + complexToken.Length).SetStyle(BaseStyleIndex);
                                    break;
                                case SyntaxStructure.TokenName.ExactAmountQuantifier:
                                    textBox.GetRange(complexToken.Index, complexToken.Index + complexToken.Length).SetStyle(_allStyles[Style.KeyLetter]);
                                    break;
                                case SyntaxStructure.TokenName.Unordered:
                                    //complexToken.Children[0] is whitespace, which should have no style.
                                    textBox.GetRange(complexToken.Children[1].Index, complexToken.Children[1].Index + complexToken.Length - complexToken.Children[0].Length).SetStyle(BaseStyleIndex);
                                    break;
                                case SyntaxStructure.TokenName.MultiLine:
                                    //Some of the first and last children are whitespace, which should have no style.
                                    var patternStartIndex = isReplacePattern ? 2 : 1;
                                    var patternEnd = complexToken.Children[patternStartIndex].Index + complexToken.Children.Skip(patternStartIndex).Take(5).Sum(c => c.Length);
                                    textBox.GetRange(complexToken.Children[patternStartIndex].Index, patternEnd).SetStyle(BaseStyleIndex);
                                    break;
                            }
                            Highlight(complexToken.Children);
                            break;
                        case not null:
                            switch (token.Name)
                            {
                                case SyntaxStructure.TokenName.Demarcate:
                                    textBox.GetRange(token.Index, token.Index + token.Length).SetStyle(_allStyles[Style.Separator]);
                                    break;
                                case SyntaxStructure.TokenName.Modifier:
                                    textBox.GetRange(token.Index, token.Index + token.Length).SetStyle(_allStyles[Style.KeyLetter]);
                                    break;
                            }
                            break;
                    }
                }
            }
        }

        public void StyleMatches(FastColoredTextBox inputTextbox, FastColoredTextBox outputTextbox, RegexerResult result)
        {
            if (result.Matches == null || _monoColouredHighlight) return;
            _labelStyleIndices.Clear();
            _findStylingOrder.Clear();
            _replaceStylingOrder.Clear();

            for (var i = 0; i < result.Matches[0].InputMatch.IndividualMatches.Count; i++)
            {
                if (i == IndividualMatchStyles.Length) i = 0;
                var findMatch = result.Matches[0].InputMatch.IndividualMatches[i];
                var replaceMatches = result.Matches[0].OutputMatch.IndividualMatches;
                _labelStyleIndices.Add(findMatch.Label, Range.ToStyleIndex(i + 1));
                if(_patternUmLabels.Contains(findMatch.Label))
                {
                    _findStylingOrder.Insert(0, i);
                    if (replaceMatches.Count > _replaceStylingOrder.Count && replaceMatches[_replaceStylingOrder.Count].Label == findMatch.Label)
                        _replaceStylingOrder.Insert(0, _replaceStylingOrder.Count);
                }
                else
                {
                    _findStylingOrder.Add(i);
                    if (replaceMatches.Count > _replaceStylingOrder.Count && replaceMatches[_replaceStylingOrder.Count].Label == findMatch.Label)
                        _replaceStylingOrder.Add(_replaceStylingOrder.Count);
                }
            }

            for (var i = 0; i < result.Matches.Length; i++)
            {
                var matchPair = result.Matches[i];
                Range matchRange;
                StyleIndex styleIndex;
                if (matchPair.InputMatch.IndividualMatches.Count == 0) continue;
                foreach (var index in _findStylingOrder)
                {
                    var individualMatch = matchPair.InputMatch.IndividualMatches[index];
                    styleIndex = _labelStyleIndices[individualMatch.Label];
                    foreach (var capture in individualMatch.Captures)
                    {
                        matchRange = inputTextbox.GetRange(capture.Index, capture.Index + capture.Length);
                        matchRange.SetStyle(styleIndex);
                    }
                }

                foreach (var index in _replaceStylingOrder)
                {
                    //if()
                    var individualMatch = matchPair.OutputMatch.IndividualMatches[index];
                    styleIndex = _labelStyleIndices[individualMatch.Label];
                    foreach (var capture in individualMatch.Captures)
                    {
                        matchRange = outputTextbox.GetRange(capture.Index, capture.Index + capture.Length);
                        matchRange.SetStyle(styleIndex);
                    }
                }
            }
        }

        public void PopulateSubMatches(DataGridView inputGrid, DataGridView outputGrid, RegexerResult result, bool limit)
        {
            _labelStyleBrushes.Clear();

            for (var i = 0; i < result.Matches[0].InputMatch.IndividualMatches.Count; i++)
            {
                if (i == IndividualMatchStyles.Length) i = 0;
                var match = result.Matches[0].InputMatch.IndividualMatches[i];
                inputGrid.Columns.Add(match.Label, match.Label);
                outputGrid.Columns.Add(match.Label, match.Label);
                var brush = _monoColouredHighlight ? (SolidBrush)Brushes.Black : (SolidBrush)IndividualMatchStyles[i].ForeBrush;
                inputGrid.Columns[i].HeaderCell.Style.ForeColor = brush.Color;
                outputGrid.Columns[i].HeaderCell.Style.ForeColor = brush.Color;
                _labelStyleBrushes.Add(match.Label, brush);
            }

            //inputGrid.RowHeadersVisible = false; //Disabling and re-enabling this after the for-loop saves performance, but it's not needed with the limit
            //TODO: find a way to save performance without limiting the number of rows. Take a look at https://stackoverflow.com/questions/10226992/slow-performance-in-populating-datagridview-with-large-data, https://10tec.com/articles/why-datagridview-slow.aspx
            var rowCount = limit ? Math.Min(result.Matches.Length, 20) : result.Matches.Length;
            for (var i = 0; i < rowCount; i++)
            {
                var matchPair = result.Matches[i];
                SolidBrush brush;
                if (matchPair.InputMatch.IndividualMatches.Count == 0) continue;
                var dataGridRow = inputGrid.Rows[inputGrid.Rows.Add()];
                dataGridRow.HeaderCell.Value = (dataGridRow.Index + 1).ToString();
                foreach (var individualMatch in matchPair.InputMatch.IndividualMatches)
                {
                    brush = _labelStyleBrushes[individualMatch.Label];
                    dataGridRow.Cells[individualMatch.Label].Value = new CellMatchData(individualMatch.Captures, brush);
                }

                if (matchPair.OutputMatch != null)
                {
                    dataGridRow = outputGrid.Rows[outputGrid.Rows.Add()];
                    dataGridRow.HeaderCell.Value = (dataGridRow.Index + 1).ToString();
                    foreach (var individualMatch in matchPair.OutputMatch.IndividualMatches)
                    {
                        brush = _labelStyleBrushes[individualMatch.Label];
                        dataGridRow.Cells[individualMatch.Label].Value = new CellMatchData(individualMatch.Captures, brush);
                    }
                }
            }
        }

        public void ClearMatchStyles(FastColoredTextBox inputTextbox, FastColoredTextBox outputTextbox)
        {
            inputTextbox.Range.ClearStyle(BaseStyleIndex);
            outputTextbox.Range.ClearStyle(BaseStyleIndex);
            for (var i = 0; i < IndividualMatchStyles.Length; i++)
            {
                inputTextbox.Range.ClearStyle(Range.ToStyleIndex(i + 1)); //+1 because BaseStyle is the first
                outputTextbox.Range.ClearStyle(Range.ToStyleIndex(i + 1));
            }
        }

        public void SetSuggestionMode(bool showSuggestionsOnCommand) => _showSuggestionsOnCommand = showSuggestionsOnCommand;

        public void SetHighlightMode(bool partialHighlighting) => _monoColouredHighlight = partialHighlighting;

        private enum Style{ Escape, Label, Separator, KeyLetter, Regex, BaseLight }

        public class CellMatchData
        {
            public List<MatchData> MatchDataCaptures { get; set; }
            public Brush TextBrush { get; set; }

            public CellMatchData(List<MatchData> matchDataCaptures, Brush textBrush)
            {
                MatchDataCaptures = matchDataCaptures;
                TextBrush = textBrush;
            }

            public static string PositionString(MatchData matchData) =>
                matchData.Length == 0 ? string.Empty : $" ({matchData.Index} - {matchData.Index + matchData.Length})";

            private string? _cachedToString;
            public override string ToString()
            {
                return _cachedToString ??=
                    string.Join('\n', MatchDataCaptures.Select(m => $"{m.Text}{PositionString(m)}"));
            }
        }
    }
}
